-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(bc5215)",
			inactive_border = "rgb(b7b5ac)",
		},
	},
	group = {
		col = {
			border_active = "rgb(bc5215)",
			border_inactive = "rgb(b7b5ac)",
			border_locked_active = "rgb(af3029)",
			border_locked_inactive = "rgb(b7b5ac)",
		},
		groupbar = {
			col = {
				active = "rgb(bc5215)",
				inactive = "rgb(b7b5ac)",
				locked_active = "rgb(af3029)",
				locked_inactive = "rgb(b7b5ac)",
			},
		},
	},
})
