# mpv各种插件
# https://github.com/stax76/awesome-mpv
# https://github.com/mpv-player/mpv/wiki/User-Scripts
# https://github.com/vommie/mpv-scripts
# https://github.com/dyphire/mpv-scripts
# https://github.com/stax76/mpv-scripts
# https://github.com/mpv-easy/mpv-easy

# mpv-ui
# https://github.com/tomasklaen/uosc
# https://github.com/brahmkshatriya/material-osc
# https://github.com/mpv-easy/mpv-easy

# mpv的各种版本
# https://github.com/mgth/mpv-omniphony

# 默认开启gpu 加速
vo=gpu

# 全屏
# fullscreen=yes

# 从视频上次退出的位置播放
# save-position-on-quit

# 字幕
sub-auto=all

# 自动硬解，但强制拷贝数据到CPU内存；兼容性更好
hwdec=auto-copy

# uosc
osc=no
osd-bar=no # 关闭默认拖动进度条动画
border=no
keep-open=yes
keepaspect-window=no

# thumbfast.lua插件。鼠标悬浮进度条显示的缩略图
script-opts-append=thumbfast-max_height=640
script-opts-append=thumbfast-max_width=360
script-opts-append=thumbfast-hwdec=yes
script-opts-append=thumbfast-network=yes
